export const ADD_ITEM = 'ADD_TODO:ADD_ITEM';
export const CLEAR = 'ADD_TODO:CLEAR';

export const RESET = 'ADD_TODO:RESET';

export const FETCH_ITEMS = 'ADD_TODO:FETCH_ITEMS';
export const FETCH_ITEMS_PENDING = 'ADD_TODO:FETCH_ITEMS_PENDING';
export const FETCH_ITEMS_FULFILLED = 'ADD_TODO:FETCH_ITEMS_FULFILLED';
export const FETCH_ITEMS_REJECTED = 'ADD_TODO:FETCH_ITEMS_REJECTED';
export const FETCH_ITEMS_ABORT = 'ADD_TODO:FETCH_ITEMS_ABORT';
